#!/usr/bin/env node
// Copies the job-kit UI exports (profiles/data/job_kits/<market>/export/*.json) into
// lib/kits/generated/, extracts each market's parameter values from parameters.yaml (the formulas
// need them; the exports do not carry them), and writes lib/kits/generated/index.ts, which imports
// everything statically so `next build` and the single-file demo both include the kits.
// Usage: npm run sync-kits            (write)
//        npm run sync-kits -- --check (exit 1 if lib/kits/generated is stale)
// The JSON is copied byte for byte. Do not edit generated files; edit the profiles and re-export.
import fs from "node:fs";
import path from "node:path";

const web = path.resolve(import.meta.dirname, "..");
const src = path.resolve(web, "../../profiles/data/job_kits");
const out = path.join(web, "lib/kits/generated");
const check = process.argv.includes("--check");

/** Minimal reader for the `parameters:` block of parameters.yaml: `  name:` then `    value: '1.2'`. */
function readParameters(text) {
  const params = {};
  let inBlock = false; let current = null;
  for (const raw of text.split(/\r?\n/)) {
    if (/^\S/.test(raw)) { inBlock = raw.startsWith("parameters:"); current = null; continue; }
    if (!inBlock) continue;
    let m;
    if ((m = /^ {2}([A-Za-z_]\w*):\s*$/.exec(raw))) { current = m[1]; continue; }
    if (current && (m = /^ {4}value:\s*['"]?(-?\d+(?:\.\d+)?)['"]?\s*$/.exec(raw))) { params[current] = m[1]; current = null; }
  }
  return params;
}

function plan() {
  const files = new Map(); // relative path in out -> content
  const kits = []; const markets = [];
  for (const market of fs.readdirSync(src).sort()) {
    const dir = path.join(src, market);
    if (!fs.statSync(dir).isDirectory()) continue;
    const exp = path.join(dir, "export");
    if (!fs.existsSync(exp)) continue;
    for (const f of fs.readdirSync(exp).filter((n) => n.endsWith(".json")).sort()) {
      const content = fs.readFileSync(path.join(exp, f), "utf8");
      JSON.parse(content); // fail loudly on a broken export
      files.set(`${market}/${f}`, content);
      kits.push({ market, file: f });
    }
    const pf = path.join(dir, "parameters.yaml");
    const params = fs.existsSync(pf) ? readParameters(fs.readFileSync(pf, "utf8")) : {};
    if (fs.existsSync(pf) && Object.keys(params).length === 0) throw new Error(`no parameters read from ${pf}`);
    files.set(`${market}/parameters.json`, JSON.stringify(params, null, 2) + "\n");
    markets.push(market);
  }
  const id = (s) => s.replace(/\W/g, "_");
  const lines = [
    "// Generated by scripts/sync-kits.mjs from profiles/data/job_kits. Do not edit; run `npm run sync-kits`.",
    "// Synthetic/illustrative seed data: not licensed, tradesperson review required.",
    ...kits.map((k) => `import ${id(`k_${k.market}_${k.file}`)} from "./${k.market}/${k.file}";`),
    ...markets.map((m) => `import ${id(`p_${m}`)} from "./${m}/parameters.json";`),
    "",
    "export interface GeneratedKit { key: string; market: string; file: string; data: unknown }",
    "export const GENERATED_KITS: readonly GeneratedKit[] = [",
    ...kits.map((k) => `  { key: "${k.market}/${k.file.replace(/\.json$/, "")}", market: "${k.market}", file: "${k.file}", data: ${id(`k_${k.market}_${k.file}`)} as unknown },`),
    "];",
    "export const MARKET_PARAMETERS: Readonly<Record<string, Readonly<Record<string, string>>>> = {",
    ...markets.map((m) => `  ${JSON.stringify(m)}: ${id(`p_${m}`)},`),
    "};",
    "",
  ];
  files.set("index.ts", lines.join("\n"));
  return files;
}

function listOut(dir, base = "") {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).flatMap((n) => {
    const p = path.join(dir, n); const rel = base ? `${base}/${n}` : n;
    return fs.statSync(p).isDirectory() ? listOut(p, rel) : [rel];
  });
}

const files = plan();
const existing = listOut(out);
const stale = [...files].filter(([rel, c]) => !fs.existsSync(path.join(out, rel)) || fs.readFileSync(path.join(out, rel), "utf8") !== c).map(([rel]) => rel);
const extra = existing.filter((rel) => !files.has(rel));
if (check) {
  if (stale.length || extra.length) {
    console.error(`lib/kits/generated is stale (${[...stale, ...extra].join(", ")}). Run: npm run sync-kits`);
    process.exit(1);
  }
  console.log(`lib/kits/generated is up to date (${files.size} files)`);
} else {
  for (const rel of extra) fs.rmSync(path.join(out, rel));
  for (const [rel, c] of files) { fs.mkdirSync(path.dirname(path.join(out, rel)), { recursive: true }); fs.writeFileSync(path.join(out, rel), c); }
  console.log(`synced ${files.size} files into lib/kits/generated (${stale.length} changed, ${extra.length} removed)`);
}
