#!/usr/bin/env python3
"""Refresh UK bank holidays in profiles/uk*.yaml from GOV.UK (https://www.gov.uk/bank-holidays.json).

Usage:
  python scripts/update_bank_holidays.py --fetch            # download, snapshot, rewrite profiles
  python scripts/update_bank_holidays.py                    # rewrite profiles from the snapshot

The snapshot lives in profiles/data/gov-uk-bank-holidays.json so tests run offline. Each profile has a
generated block delimited by `# BEGIN gov.uk bank holidays (<division>)` / `# END gov.uk bank holidays`.
England and Wales, Scotland and Northern Ireland differ; GOV.UK is the primary source.
"""

from __future__ import annotations

import argparse
import json
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / "profiles" / "data" / "gov-uk-bank-holidays.json"
URL = "https://www.gov.uk/bank-holidays.json"
TARGETS = {
    "england-and-wales": ROOT / "profiles" / "uk.yaml",
    "scotland": ROOT / "profiles" / "uk-scotland.yaml",
    "northern-ireland": ROOT / "profiles" / "uk-ni.yaml",
}
RANGE = ("2026-01-01", "2028-12-31")


def block(division: str, events: list[dict[str, str]], indent: str) -> str:
    head = f"{indent}holidays:  # BEGIN gov.uk bank holidays ({division})"
    lines = [head + "; generated by scripts/update_bank_holidays.py"]
    for e in sorted(events, key=lambda x: x["date"]):
        if RANGE[0] <= e["date"] <= RANGE[1]:
            note = e["title"] + (f" ({e['notes']})" if e.get("notes") else "")
            lines.append(f"{indent}  - {e['date']}  # {note}")
    lines.append(f"{indent}  # END gov.uk bank holidays")
    return "\n".join(lines)


def rewrite(path: Path, division: str, events: list[dict[str, str]]) -> None:
    text = path.read_text(encoding="utf-8")
    pattern = re.compile(
        r"^(?P<indent>[ ]*)holidays:[^\n]*BEGIN gov\.uk bank holidays[^\n]*\n"
        r"(?:.*\n)*?[ ]*# END gov\.uk bank holidays",
        re.MULTILINE,
    )
    m = pattern.search(text)
    if not m:
        raise SystemExit(f"{path}: no generated holidays block found")
    new = block(division, events, m["indent"])
    path.write_text(text[: m.start()] + new + text[m.end():], encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--fetch", action="store_true")
    args = ap.parse_args()
    if args.fetch:
        with urllib.request.urlopen(URL, timeout=30) as r:  # noqa: S310 - fixed GOV.UK URL
            SNAPSHOT.write_bytes(r.read())
    data = json.loads(SNAPSHOT.read_text(encoding="utf-8"))
    for division, path in TARGETS.items():
        rewrite(path, division, data[division]["events"])
        print(f"updated {path.relative_to(ROOT)} ({division})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
